spring:
  profiles:
    active: ${PROFILE:dev}
  config:
    import: optional:configserver:${CONFIG_SERVER_URL:http://127.0.0.1:9997}
  cloud:
    config:
      label: ${CONFIG_BRANCH:master}
      username: ${SERVER_USER:geek}
      password: ${SERVER_PASS:geek_pass}

